 # .travis.yml
sudo: false
language: node_js
node_js:
  - '0.12'
script: gulp gh
env:
  global:
  - GH_REF: github.com/webcaetano/test-static.git
  - secure: RGb9ZyUxZE4OLeQ0r4ztZL0XBzg1XVmL7jQp8k56Fcnxk+7KiG6RIiB8r5ALE4ZUdNcN91pfoMqiO/Fp611PtbJtxatFKh65/IeaYkMnikm7lGwgehcZzLxY7DLbd63hslgJl60vPhf4nWZuspIle598Aw1laF3cAlkNgBn+vjYA6qYvoaKSQTGpuKFJXMGYJm+5ndUxBjhUI+ukFIjDqEtPuoxlVuBZrglO8MAEHj+EefyCEUJMaqw63T4ap0PI3mcOZ9DIqHJzrzxbMpOeM7jbV6w7xiq1uFRNDZlmtIJg7UqvlVLfI9QIxJw+RfgKO5Cr0W4ihJL4myZhq9cnKBxTr69vQBesgPgv/utGLA0pTEmD+JeJiGSet5xTJLHaSalkl8CE6BQjLwR+YANfPdUHXnzjtycIzEFvRNrnamteNoo740r3uhjxA+idFpkfwggUKsxaMC9r6w7avJdoRnSp5Pdll284SYaSd/l2m/L7u5syuRyYHK0RxjjhS2EsCJ4GmiBU5viunIF+X2Dz0bwa7WX8648Cxg2DwpU/Zw83Y4eGJR1i7aIBUKLLa5RrqxLJ+KT84MaiDbten1faiWBaBJQ5gFSCIdB3acFytiziBmQHPc2b9xGScXMcsj6vguwMUnlYtB++eMx8hCo4qM7X3eIpxtJJefvUjHl9OI4=
before_script:
  - npm install -g bower
  - npm install -g gulp
  - bower install
